# This is a basic workflow to help you get started with Actions
# It triggers on each push to the main branch and sets up AIO CLI using "AIO CLI Setup - Action" and then installs the plugin for cloud manager on top of the existing CLI.
name: AEM Test

on: 
 workflow_dispatch:
  inputs:
   env:
    description: 'Env Name'
    default: 'dev'
    type: environment

    
jobs:
  Configure-Adobe-IO:
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.1.0
      
      - name: Install CM plugin
        run: aio plugins:install @adobe/aio-cli-plugin-cloudmanager
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Decrypt large secret
        run: |
          chmod 775 * 
          sh decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          
      
      - name: Configure Authentication
        run: |
           echo You Selected ${{ inputs.env }}
           cat $HOME/secrets/config.json
           aio config:set ims.contexts.aio-cli-plugin-cloudmanager $HOME/secrets/config.json --file --json
           aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key ./private.key --file
           
           
